# Generated by Django 3.2.9 on 2021-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie', verbose_name='image')),
                ('category', models.CharField(choices=[('AC', 'action'), ('DR', 'drama'), ('RM', 'romance'), ('CM', 'comedy')], max_length=10, verbose_name='category')),
                ('language', models.CharField(choices=[('EN', 'english'), ('SP', 'spanish'), ('FR', 'france')], max_length=10, verbose_name='language')),
                ('status', models.CharField(choices=[('RA', 'recently added'), ('MW', 'most watched'), ('TR', 'top rated')], max_length=10, verbose_name='status')),
                ('year_of_production', models.DateTimeField(auto_now_add=True, verbose_name='year of production')),
                ('views_count', models.IntegerField(default=0, verbose_name='views count ')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
