# Generated by Django 3.2.9 on 2021-11-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
