# Generated by Django 3.2.9 on 2021-11-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField(verbose_name='links')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_movie_links', to='movie.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'MovieLinks',
                'verbose_name_plural': 'MovieLinkss',
            },
        ),
        migrations.CreateModel(
            name='WatchedLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField(verbose_name='links')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_movie_links', to='movie.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'MovieLinks',
                'verbose_name_plural': 'MovieLinkss',
            },
        ),
        migrations.DeleteModel(
            name='MovieLinks',
        ),
    ]
