# Generated by Django 3.2.9 on 2021-11-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20211110_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField(verbose_name='links')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'DownloadLink',
                'verbose_name_plural': 'DownloadLinks',
            },
        ),
        migrations.CreateModel(
            name='WatchedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField(verbose_name='links')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'WatchedLink',
                'verbose_name_plural': 'WatchedLinks',
            },
        ),
        migrations.RemoveField(
            model_name='watchedlinks',
            name='movie',
        ),
        migrations.DeleteModel(
            name='DownloadLinks',
        ),
        migrations.DeleteModel(
            name='WatchedLinks',
        ),
    ]
