# Generated by Django 3.2.9 on 2021-11-10 16:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20211110_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('action', 'action'), ('drama', 'drama'), ('romance', 'romance'), ('comedy', 'comedy')], max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('EN', 'english'), ('SP', 'spanish'), ('FR', 'france')], max_length=30, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'recently added'), ('MW', 'most watched'), ('TR', 'top rated')], max_length=30, verbose_name='status'),
        ),
    ]
