# Generated by Django 3.2.9 on 2021-11-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20211110_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('romance', 'ROMANCE'), ('comedy', 'COMEDY')], max_length=50, verbose_name='category'),
        ),
    ]
