# Generated by Django 3.2.9 on 2021-11-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('korean', 'KOREAN')], max_length=30, verbose_name='language'),
        ),
    ]
