# Generated by Django 3.2.9 on 2021-11-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_of_production',
            field=models.DateTimeField(verbose_name='year of production'),
        ),
    ]
